arena_app/config/routes.rb
Rails.application.routes.draw do



  default_url_options :host => "localhost:3000"
  root 'static_pages#home'

  get 'password_resets/new'
  get 'password_resets/edit'


  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  #gamer
  get  '/signup',  to: 'gamers#new'
  #session
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/attributes', to: 'account_attributes#new'
  post '/attributes', to: 'account_attributes#create'

  #oauth
  get 'loginGoogle', to: redirect('/auth/google_oauth2') # , as: 'login'
  get 'logoutGoogle', to: 'sessions#destroy' # , as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create_by_google_oauth'
  get 'auth/failure', to: redirect('/')

  #arena
  get '/arena',  to: 'arena_pages#arena'
  get '/changerole', to: 'arena_pages#changerole'
  get '/upgrade', to: 'arena_pages#upgrade' #È IL BOTTONE PER CAMBIARE RUOLO
  get '/downgrade', to: 'arena_pages#downgrade'

  #chatroom
  get '/chat', to: 'chatrooms#index'

  #errors
   get '/404', to: 'errors#not_found'
   get '/500', to: 'errors#internal_server_error'

  resources :teams do
    #get 'join'
    get 'send_invite'
    get 'leave'
    get 'show_invites'
    get 'add_challenge'
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    resources :invite_requests, only:[:index,:show,:create,:destroy] do
      get 'accept'
      get 'refuse'

    end
    resources :challenges do
      get'accept'
      get'refuse'
    end
    resources :matches do
      get'ragequit'
      get'register'

    end
  end
  get '/my_groups', to: 'groups#my_groups'
  resources :groups do
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    get 'join'
    get 'leave'
  end
  resources :gamers
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_attributes

  resources :consoles
  resources :games



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

arena_app/app/models/match.rb
class Match < ApplicationRecord
#	validate :must_have_challenge

	belongs_to :team
	belongs_to :matching_team, class_name: 'Team'

	def must_have_challenge # 1..*
		errors.add(:base, 'Must have been challenged first') if !team.challenging_teams.to_a.include?(matching_team) 
	end
end

arena_app/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  load_and_authorize_resource :team
  load_and_authorize_resource :match, through: :team
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @team=Team.find([:team_id])
    @match = @team.matches.build
  end

  # GET /matches/1/edit
  def edit
    
    @match= Match.find(params[:id])
    
  end

  # POST /matches
  # POST /matches.json
  def create

    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @team = Team.find(params[:team_id])
    @match.disputed = true
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to team_matches_path(@team), notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to team_matches_url(@team), notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ############ NO CRUD 

  def ragequit 
    @team = Team.find_by_id(params[:team_id])
    @mat=Match.find_by_id(params[:match_id])
    if @team.nil? || current_gamer.team.nil?
      flash[:danger]="not found this team"
    elsif @mat.nil?
      flash[:danger]="not found this invite request"
    else
      @mat.update_attribute(:score,-1)
      @mat.update_attribute(:disputed, true)
      flash[:success]="RageQuitted"
      @team.matches.delete(@mat)
      
    end
    render :index
  end

  def register
    @team = Team.find_by_id(params[:team_id])
    @team=Challenge.find_by_id(params[:challenge_id])
    if @team.nil? || current_gamer.team.nil?
      flash[:danger]="not found this team"
    elsif existing_match?(@team,current_gamer.team)
      flash[:warning]="match already exists"
    elsif @cha.nil?
      flash[:danger]="not found this invite request"
    else
      flash[:success]="Removed challenge"
      @team.challenges.delete(@cha)
      @cha.destroy
    end
    render :index
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def match_params
    #   params.fetch(:match, :mat_score, :score)
    # end


  def match_params
    params.require(:match).permit(:match, :mat_score, :score, :team_id)
  end

end

arena_app/app/helpers/matches_helper.rb
module MatchesHelper
	def display_score(score)
		if score.nil?
			return ""
		elsif score < 0
			return "Retreat"
		else
			return score.inspect
		end
	end

	def display_no_score
		"[ | ]"
	end
end

arena_app/app/views/matches/_form.html.erb
<%= form_with(model: match,local: true, :url => {action: "update", team_id: @team ,id: @match }  ) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :score, title: "Set your score" %>
    <%= form.number_field :score, within: 0...13 %>
  </div>

  <div class="field">
    <%= form.label :mat_score,title: "Set opposite score" %>
    <%= form.number_field :mat_score, within: 0...13  %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

arena_app/app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', team_match_path(@team,@match) %> |
<%= link_to 'Back', team_matches_path(@team) %>

arena_app/app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Matches") %>
<h1>Matches</h1>

<table>
  <thead>
    <tr>
    <th>Match<th>
      <th>Opponent</th>
      <th>Score</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <%if !@matches.nil? %>
    <% @matches.each_with_index do |match,i| %>
    <tr>
      <td>
        <%=link_to '<i class="glyphicon glyphicon-arrow-right"></i>'.html_safe, team_match_path(@team,match),class: "btn btn-default btn-m btn-warning",style:"color:black" %>
      </td>
        
      <td>
        <%=link_to match.matching_team.name, team_path(@team),class: "btn btn-default btn-m" %>
      </td>
      <% if match.disputed %>
      
      <td>
        [
        <%= display_score(match.score)+" " %>|
        <%= " "+ display_score(match.mat_score.to_i) %>
        ]
      </td>
      <% else %>
      
      <td><%=display_no_score%></td>
      <td>
        <%= link_to 'RageQuit',team_match_ragequit_path(match_id: match.id),class:"btn btn-default btn-l" %>
      </td>
      <td>
        <%= link_to 'Register score', edit_team_match_path(id: match.id),class:"btn btn-default btn-l" , data: { confirm: 'Are you sure? Match will be considered concluded' } %>
      </td>
    </tr>
    <% end %>
    <% end %>
    <%end%>
  </tbody>
</table>
<%= link_to 'Back', team_path(@team) %>
<br>

arena_app/app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

arena_app/app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>
<%= provide(:title,"Match")%>

	<div class="container-fluid">
	<%if !@match.nil? %>
		<div class="row">
		<div class="col-md-4 ">
			<%= link_to @match.team.name, team_path(@match.team),class: "btn btn-default btn-block btn-warning", style: "color:black; font-size:40px;" %> 
		</div>
		<div class="col-md-1"><%= image_tag @match.team.avatar.url(:thumb),width: 100, class: "avatar-image "%></div>
		<div class="col-md-4">
			
		</div>
		</div>
		<div class="row">
		<div class="col-md-4" id="score"><% if @match.disputed %> <%=@match.score.to_s%> <%end%></div>
		<div class="col-md-2">
			<%= image_tag "versus.png",width:80 %>
		</div>
		<div class="col-md-4"  id="score"> <% if @match.disputed %> <%=@match.mat_score.to_s%><%end%></div>
		
		</div>
		<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-1"><%= image_tag @match.matching_team.avatar.url(:thumb),width: 100, class: "avatar-image "%></div>
		<div class="col-md-4" >
			 <%= link_to @match.matching_team.name, team_path(@match.matching_team),class: "btn btn-default btn-block btn-danger"  , style: "color:black; font-size:40px;"%> 
		</div>
		
		</div>
	<% end %>
	</div>

<%= link_to 'Edit', edit_team_match_path(@team,@match),class: "btn btn-default btn-xs" %> 
<%= link_to 'Back', team_matches_path(@team),class: "btn btn-default btn-xs" %>