arena_app/config/routes.rb
Rails.application.routes.draw do



  default_url_options :host => "localhost:3000"
  root 'static_pages#home'

  get 'password_resets/new'
  get 'password_resets/edit'


  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  #gamer
  get  '/signup',  to: 'gamers#new'
  #session
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/attributes', to: 'account_attributes#new'
  post '/attributes', to: 'account_attributes#create'

  #oauth
  get 'loginGoogle', to: redirect('/auth/google_oauth2') # , as: 'login'
  get 'logoutGoogle', to: 'sessions#destroy' # , as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create_by_google_oauth'
  get 'auth/failure', to: redirect('/')

  #arena
  get '/arena',  to: 'arena_pages#arena'
  get '/changerole', to: 'arena_pages#changerole'
  get '/upgrade', to: 'arena_pages#upgrade' #È IL BOTTONE PER CAMBIARE RUOLO
  get '/downgrade', to: 'arena_pages#downgrade'

  #chatroom
  get '/chat', to: 'chatrooms#index'

  #errors
   get '/404', to: 'errors#not_found'
   get '/500', to: 'errors#internal_server_error'

  resources :teams do
    #get 'join'
    get 'send_invite'
    get 'leave'
    get 'show_invites'
    get 'add_challenge'
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    resources :invite_requests, only:[:index,:show,:create,:destroy] do
      get 'accept'
      get 'refuse'

    end
    resources :challenges do
      get'accept'
      get'refuse'
    end
    resources :matches do
      get'ragequit'
      get'register'

    end
  end
  get '/my_groups', to: 'groups#my_groups'
  resources :groups do
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    get 'join'
    get 'leave'
  end
  resources :gamers
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_attributes

  resources :consoles
  resources :games



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

arena_app/app/models/group.rb
class Group < ApplicationRecord
  validates :name, length: {minimum: 3,maximum: 40},
                         presence: true

  validates :console, presence:true
  #validates :games,length:{minimum:1} #not working
  

  has_many :chatrooms, dependent: :destroy
  has_many :playings
  has_many :games , through: :playings, dependent: :destroy

  has_many :gamers_groups
  has_many :members, through: :gamers_groups, source: :gamer, dependent: :destroy


  belongs_to :creator,class_name: "Gamer"

  belongs_to :console

 
end

arena_app/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :check_attributes
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
   @group = Group.find(params[:id])
 end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    #salvo il gruppo nel gamer
    @group.creator=current_gamer
    if @group.region != @group.creator.nation
               flash.now[:danger] = "different nation selected: #{@group.creator.nation}  #{@group.region}"
               render 'new'
    else

    @group.members << current_gamer

    respond_to do |format|
       if @group.save
            format.html { redirect_to @group, notice: 'Group was successfully created.' }
            format.json { render :show, status: :created, location: @group }
       else
          format.html { render :new }
          format.json { render json: @group.errors, status: :unprocessable_entity }
       end
    end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        if @group.region != @group.creator.nation
           flash.now[:danger] = "different nation selected: #{@group.creator.nation} #{@group.region}"
           format.html { render :edit }
        else
            format.html { redirect_to @group, notice: 'Group was successfully updated.' }
            format.json { render :show, status: :ok, location: @group }
        end
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    #puts "---------->"+current_member.id.to_s
    @group =Group.find(params[:group_id])
    #puts "---------->"+ @group.id.to_s
    @group.members << Gamer.find_by_id(current_gamer.id) unless current_gamer.groups.include?(@group) || @group.members.include?(current_gamer)
    # @member = current_gamer.groups.build(params[:id])
    # @group = @member.build_group(params[:group])
    redirect_to @group
  end

  def leave

    @group =Group.find(params[:group_id])
    @member = @group.members.find_by_id(current_gamer.id)
    if(@group.creator==@member)
      destroy
    else
      @group.members.delete(@member) unless @member.nil?
      redirect_to @group
    end
  end

  def my_groups
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:member,:name, :region, :console_id,{:game_ids => []}, :description)
    end
  end

arena_app/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :region,"Choose your nation (same of sign up):" %>
    <%= form.select( :region,Nation.order(:name).collect {|n| [n.name,n.code]} ) %>

  </div>

  <div class="field">
  <%= form.label :console_id,"Choose your console:" %>
  <%= form.collection_select :console_id, Console.order(:name), :id, :name %>



  </div>

  <div class="field">
    <%= form.label :game_ids,"Choose your games:" %>
    

        <div class="funkyradio">
        <%= form.collection_check_boxes( :game_ids, Game.order(:name), :id, :name) do |c|%>
          <div class="funkyradio-primary">
            <%= c.check_box %> <%= c.label %>
          </div>
        <%end%>
        </div>

  <div class="field">
  <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>

  </div>

  <div class="actions">
    <%= form.submit "Save Group", class: "btn btn-primary" %>
  </div>
<% end %>

arena_app/app/views/groups/edit.html.erb
<% provide(:title, "Editing Group") %>

<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<div class= "btn btn-default btn-xs"><%= link_to 'Show', @group %></div>
<div class= "btn btn-default btn-xs"><%= link_to 'Back', groups_path %></div>

arena_app/app/views/groups/index.html.erb
<% provide(:title, "Group list") %>
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Console</th>
      <th>Game</th>
      <th>Creator</th>
      <th>Members </th>
      <th colspan="6">Functions:</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.region %></td>
        <td><%= group.console.name unless group.console.nil? %></td>
        <td> <% group.games.each do |g| %>
      <%= g.name %> <%end%></td>
      <td>    <%= group.creator.username unless group.creator.nil? %></td>
        <td> <% group.members.each do |g| %>
      <%= g.username %> -> <%= g.email %> <%end%></td>
        <td>
        <div class= "btn btn-default btn-xs"><%= link_to 'Show', group %></div>
        <div class= "btn btn-default btn-xs"><%= link_to 'Edit', edit_group_path(group) %></div>
        <div class= "btn btn-default btn-xs"><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class= "btn btn-default btn-sm"><%= link_to 'Back',  arena_path %></div>
<% if can? :create, Group %>
<div class= "btn btn-default btn-sm"><%= link_to 'New Group', new_group_path %></div>
<% end %>

arena_app/app/views/groups/my_groups.html.erb
<%= provide(:title, "My group list") %>
<p id="notice"><%= notice %></p>

<h1>These are your groups </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Console</th>
      <th>Game</th>
      <th>Members </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_gamer.groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.region %></td>
        <td><%= group.console.name %></td>
        <td> <% group.games.each do |g| %>
      <%= g.name %> <%end%></td>
        <td> <% group.members.each do |g| %>
      <%= g.username %> -> <%= g.email %> <%end%></td>
      
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back',  arena_path %>
<% if current_gamer.admin? %>
  <%= link_to 'New Group', new_group_path %>
<% end %>

arena_app/app/views/groups/new.html.erb
<% provide(:title, "New Group") %>

<h1>New Group</h1>

<%= render 'form', group: @group %>

<div class= "btn btn-default btn-xs"><%= link_to 'Back', groups_path %></div>

arena_app/app/views/groups/show.html.erb
<% provide(:title, "Showing group") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @group.creator.username %> -> <%= @group.creator.email %>
</p>

<p>
  <strong>Region:</strong>
  <%= @group.region %>
</p>

<p>
  <strong>Console:</strong>
  <%= @group.console.name  %>
</p>

<p>
  <strong>Game:</strong>

  [
    <% @group.games.each do |g| %>
      <%= g.name %>,
    <%end%>]
</p>

<p>
<strong>Members:</strong>
<% @group.members.each do |g| %>
      <%= g.username %> -> <%= g.email %>
    <%end%>
</p>
<% if !@group.members.include?(current_gamer)%>
<%= link_to 'Join this group', group_join_path(@group) ,class: "btn btn-default btn-sm"%>
<% end %>
<% if @group.creator == current_gamer %>
  <div class= "btn btn-default btn-sm"><%= link_to 'Leave this group', group_leave_path(@group), data: { confirm: "Group will be deleted, are you sure?" } %></div>
  <% else %>
  <%= link_to 'Leave this group', group_leave_path(@group),class: "btn btn-default btn-sm" %>
  <% end %>
<% if can? :edit, @group %>
  <div class= "btn btn-default btn-sm"><%= link_to 'Edit', edit_group_path(@group) %></div>
<% end %>




  <br>
  <table>
  <th>Chatroom:</th>
  <tbody>
      <% @group.chatrooms.each do |chatroom| %>
        <tr>
          <td><%= chatroom.name %></td>
          <td>
            <% if @group.creator == current_gamer %>
              <div class= "btn btn-default btn-sm"><%= link_to 'Destroy ', group_chatroom_path(chatroom.group_id, chatroom), method: :delete, data: { confirm: 'Are you sure?' } %></div>
            <% end %>
          </td>
          <td></td>
          <td>
            <% if @group.creator == current_gamer %>
              <div class= "btn btn-default btn-sm"><%= link_to 'ChangeChatroomName', edit_group_chatroom_path(chatroom.group_id, chatroom) %></div></td>
            <% end %>
          <td></td>
            <% if @current_gamer.groups.include? @group %>
              <td><div class= "btn btn-default btn-sm"><%= link_to 'JoinChatroom', group_chatroom_chatroom_users_path(chatroom.group_id, chatroom), method: :post %></div></td>
            <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if @group.creator == current_gamer %>
    <div class= "btn btn-default btn-sm"><%= link_to 'New Chatroom', new_group_chatroom_path(@group) %></div>
  <% end %>
  <br/>
  <br/>
  <br/>
  <div class= "btn btn-default btn-xs"><%= link_to 'Back', groups_path %></div>