arena_app/config/routes.rb
Rails.application.routes.draw do



  default_url_options :host => "localhost:3000"
  root 'static_pages#home'

  get 'password_resets/new'
  get 'password_resets/edit'


  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  #gamer
  get  '/signup',  to: 'gamers#new'
  #session
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/attributes', to: 'account_attributes#new'
  post '/attributes', to: 'account_attributes#create'

  #oauth
  get 'loginGoogle', to: redirect('/auth/google_oauth2') # , as: 'login'
  get 'logoutGoogle', to: 'sessions#destroy' # , as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create_by_google_oauth'
  get 'auth/failure', to: redirect('/')

  #arena
  get '/arena',  to: 'arena_pages#arena'
  get '/changerole', to: 'arena_pages#changerole'
  get '/upgrade', to: 'arena_pages#upgrade' #È IL BOTTONE PER CAMBIARE RUOLO
  get '/downgrade', to: 'arena_pages#downgrade'

  #chatroom
  get '/chat', to: 'chatrooms#index'

  #errors
   get '/404', to: 'errors#not_found'
   get '/500', to: 'errors#internal_server_error'

  resources :teams do
    #get 'join'
    get 'send_invite'
    get 'leave'
    get 'show_invites'
    get 'add_challenge'
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    resources :invite_requests, only:[:index,:show,:create,:destroy] do
      get 'accept'
      get 'refuse'

    end
    resources :challenges do
      get'accept'
      get'refuse'
    end
    resources :matches do
      get'ragequit'
      get'register'

    end
  end
  get '/my_groups', to: 'groups#my_groups'
  resources :groups do
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    get 'join'
    get 'leave'
  end
  resources :gamers
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_attributes

  resources :consoles
  resources :games



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

arena_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | Players Arena</title><!--<title>ArenaApp</title> NON MI METTEVA I TITOLI PERCHE SETTAVA SEMPRE QUESTO DI BASE -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= debug(params) if Rails.env.development? %>
    </div>


    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
        </div>
        <nav>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home" , home_path ,class: "ab"%></li>
            <li><%= link_to "Help" , help_path ,class: "ab"%></li>
            <li><%= link_to "About" , about_path ,class: "ab"%></li>
                <% if logged_in? %>
                  <li><%= link_to "Arena" , arena_path ,class: "ab"%></li>
                  <li><%= link_to "Gamers", gamers_path ,class: "ab"%></li>
                  <li class="dropdown">
                  <a href="#" class="dropdown-toggle name-role" data-toggle="dropdown">
                  <%=current_gamer.role.capitalize+" "%>|
                  <%=current_gamer.email%><b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_gamer %></li>
                  <li><%= link_to "Settings", edit_gamer_path(current_gamer) %></li>
                  <%if !current_gamer.team.nil?%>
                  <li><%= link_to "Your Team", team_path(current_gamer.team) %></li>
                  <%end%>
                  <%if !current_gamer.groups.nil?%>
                  <li><%= link_to "Your Groups", my_groups_path  %></li>
                  <%end%>
                  
                  <li class="divider"></li>
                  <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                  </ul>
                  </li>
                  <% else %>
                    
                    <li><%= link_to "Log in", login_path ,class: "ab"%></li>
              <% end %>

            </ul>
        </nav>

    </header>




        <%= yield %>
  </body>
</html>