arena_app/config/routes.rb
Rails.application.routes.draw do



  default_url_options :host => "localhost:3000"
  root 'static_pages#home'

  get 'password_resets/new'
  get 'password_resets/edit'


  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/home',   to: 'static_pages#home'
  #gamer
  get  '/signup',  to: 'gamers#new'
  #session
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/attributes', to: 'account_attributes#new'
  post '/attributes', to: 'account_attributes#create'

  #oauth
  get 'loginGoogle', to: redirect('/auth/google_oauth2') # , as: 'login'
  get 'logoutGoogle', to: 'sessions#destroy' # , as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create_by_google_oauth'
  get 'auth/failure', to: redirect('/')

  #arena
  get '/arena',  to: 'arena_pages#arena'
  get '/changerole', to: 'arena_pages#changerole'
  get '/upgrade', to: 'arena_pages#upgrade' #È IL BOTTONE PER CAMBIARE RUOLO
  get '/downgrade', to: 'arena_pages#downgrade'

  #chatroom
  get '/chat', to: 'chatrooms#index'

  #errors
   get '/404', to: 'errors#not_found'
   get '/500', to: 'errors#internal_server_error'

  resources :teams do
    #get 'join'
    get 'send_invite'
    get 'leave'
    get 'show_invites'
    get 'add_challenge'
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    resources :invite_requests, only:[:index,:show,:create,:destroy] do
      get 'accept'
      get 'refuse'

    end
    resources :challenges do
      get'accept'
      get'refuse'
    end
    resources :matches do
      get'ragequit'
      get'register'

    end
  end
  get '/my_groups', to: 'groups#my_groups'
  resources :groups do
    resources :chatrooms do
      resources :chatroom_users
      resources :messages
      get 'index'
    end
    get 'join'
    get 'leave'
  end
  resources :gamers
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_attributes

  resources :consoles
  resources :games



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

arena_app/app/models/invite_request.rb
class InviteRequest < ApplicationRecord
	belongs_to :gamer, inverse_of: :invite_requests
    belongs_to :team, inverse_of: :invite_requests
end

arena_app/app/controllers/invite_requests_controller.rb
class InviteRequestsController < ApplicationController
  load_and_authorize_resource :team
  load_and_authorize_resource :invite_request, through: :team

  before_action :set_invite_request, only: [:show, :edit, :update, :destroy]

  # GET /invite_requests
  # GET /invite_requests.json
  def index
    @team = Team.find_by_id(params[:team_id])
    @invite_requests = @team.invite_requests
  end
  # GET /invite_requests/1
  # GET /invite_requests/1.json
  def show
  end

  # GET /invite_requests/new
  def new
    @invite_request = InviteRequest.new
  end

  # GET /invite_requests/1/edit
  def edit
  end

  # POST /invite_requests
  # POST /invite_requests.json
  def create
    @invite_request = InviteRequest.new(invite_request_params)

    respond_to do |format|
      if @invite_request.save
        format.html { redirect_to @invite_request, notice: 'Invite request was successfully created.' }
        format.json { render :show, status: :created, location: @invite_request }
      else
        format.html { render :new }
        format.json { render json: @invite_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invite_requests/1
  # PATCH/PUT /invite_requests/1.json
  def update
    respond_to do |format|
      if @invite_request.update(invite_request_params)
        format.html { redirect_to @invite_request, notice: 'Invite request was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite_request }
      else
        format.html { render :edit }
        format.json { render json: @invite_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invite_requests/1
  # DELETE /invite_requests/1.json
  def destroy
    @invite_request.destroy
    render :index

  end

  def accept
    @team = Team.find_by_id(params[:team_id])
    @inv=InviteRequest.find_by_id(params[:invite_request_id])
    if @team.nil?
      flash[:danger]="Not found this team"
    elsif @inv.nil?
      flash[:danger]="Not found this invite request"
    elsif @inv.gamer.team.nil?
      @team.gamers << @inv.gamer
      flash[:success]="Added gamer"
      @team.invites.delete(@inv.gamer)
      @inv.destroy
    else 
      flash[:danger]="Impossible: the gamer is altready member of a team"
    end
    render :index
  end

  def refuse
    @team = Team.find_by_id(params[:team_id])
    @inv=InviteRequest.find_by_id(params[:invite_request_id])
    if @team.nil?
      flash[:danger]="Not found this team"
    elsif @team.gamers.include?(@inv.gamer)
      flash[:warning]="Gamer already in team"
    elsif @inv.nil?
      flash[:danger]="Not found this invite request"
    else
      @team.invites.delete(@inv.gamer)
      flash[:success]="Removed invite"
      @inv.destroy
    end
    render 'index'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite_request
      @invite_request = InviteRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def invite_request_params
    #   params.fetch(:invite_request, :team_id,{})
    # end

  def invite_request_params
    params.require(:invite_request).permit(:invite_request, :team_id)
  end
end

arena_app/app/views/invite_requests/_form.html.erb
<%= form_with(model: invite_request, local: true) do |form| %>
  <% if invite_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invite_request.errors.count, "error") %> prohibited this invite_request from being saved:</h2>

      <ul>
      <% invite_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

arena_app/app/views/invite_requests/edit.html.erb
<h1>Editing Invite Request</h1>

<%= render 'form', invite_request: @invite_request %>

<%= link_to 'Show', @invite_request %> |
<%= link_to 'Back', invite_requests_path %>

arena_app/app/views/invite_requests/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Invite requests") %>
<h1>Invite Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if !@invite_requests.empty?   %>
    <%@invite_requests.each do |invite_request|%>
    <tr>
      Request from: <%= invite_request.gamer.email %>
      <td><%= link_to 'Accept', team_invite_request_accept_path(invite_request_id: invite_request.id) %></td>
      <td><%= link_to 'Refuse', team_invite_request_refuse_path(invite_request_id: invite_request.id), data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    <%else%>
      <strong>No invites request at the moment</strong>
    <%end%>
  </tbody>
</table>
<br>
<%= link_to 'Back', team_path(current_gamer.team) %>

arena_app/app/views/invite_requests/new.html.erb
<h1>New Invite Request</h1>

<%= render 'form', invite_request: @invite_request %>

<%= link_to 'Back', invite_requests_path %>

arena_app/app/views/invite_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invite_request_path(@invite_request) %> |
<%= link_to 'Back', invite_requests_path %>